### ISSUE TITLE
Bot db

### ISSUE THREAD

**Issue by adbenitez** [deltachat-bot/bot-pages#10]
In a similar(but simpler) spirit of the provider-db page, there could be a list of public bots with a description of his capabilities, so bot developers can publish their bot address there and let the users know

**Comment by Simon-Laux** [comment]
_/me is just dumping some thoughts in this comment_
I would be hesitant with the addresses though, because those bots could get alot of traffic.. but on the other hand that's a great stresstest.
Maybe we could have a field `instances: <email> <email2> <email3>` and when you visit the site you get one of them displayed at the top so we could have a bit load balancing.
Let's see, maybe we don't even need such loadbalancing.

**Comment by pabzm** [comment]
Thanks for the idea!

We've thought about this too and are going to open a forum section specifically for anything bots-related, which will include a "showcase" category, in which usable bots shall be presented.
If that showcase category gets crowded we can think about a different publishing format, but for now we want to start with a pragmatic thing (thus I'm closing this issue).

We'd like the "bots" category in the forum to open with some content, so it be created as soon as bots.delta.chat is online with enough relevant content. I'd guess in one or two weeks. Please be welcome to prepare showing off your own bots then!
