### ISSUE TITLE
Link to github organisation in footer

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat-bot/bot-pages#13]
like on the right side (float right)

**Comment by hpk42** [comment]
i think the link to the github organization should just be in the "develop" section. 
See #14 -- i think it's nice to not have a footer at all.

**Comment by Simon-Laux** [comment]
I want it as shortcut not just that it is somewhere on the site.

**Comment by ghost** [comment]
I also think it's a good idea to have the link in the footer. I don't think our footer looks bad.

**Comment by ghost** [comment]
On second thought - the GitHub organization is not really a good entry point. 

IIRC the org was founded because we wanted to offer all bots in one place. But is this really of much use? We already have the problem that we can't add the simplebot repository to the org, because it's a fork of deltabot. Other bots may be developed in a similar way, and we may run into the same problem again.

It is in general not an established practice to host community-maintained additions in a github organization. GitHub orgs are not very good for that, you can't ask questions, you don't have any onboarding, it's just a list of repositories.

As the org is used right now, we have the page and some example-bots in here. That's pretty organic, and if no new possibilities arise, that's probably how the org will be used in the future. So I don't see a good reason to link to the org itself; we should have a page for example bots (see #11), where we can also explain them better, but we shouldn't promote the org too much.

Instead we should promote the new forum category (I plan to open it tomorrow). It's easy for community members to both ask questions and introduce their new bots there. It has a bit of onboarding with discourse's about topic, and it's a social place, not a list.

I'm also in favor of linking to the new forum category in a footer, but that's an aesthetic question, as far as I understand it.

**Comment by Simon-Laux** [comment]
If this wastes too much time discussing it, I will close it.
